#!/usr/bin/env python3
import tdl, time, math, random, sys, signal

sys.path.append('generators/')
sys.path.append('lib/')
sys.path.append('nouns/')
sys.path.append('objects/')

import maps, monsters, consts, colors, utils, races, player, draw

tdl.setFont('font/terminal20x20_gs_ro.png', greyscale=True)
tdl.event.set_key_repeat(delay=40, interval=0)
GS = {}
def reset_GS():
    global GS
    
    GS = {
        'console': tdl.init(consts.WIDTH, consts.HEIGHT, 'Last Man Standing', renderer=u'GLSL'),
        'screen': 'INTRO',
        'player': player.Player(races.WARRIOR),
        'terrain_map': maps.TerrainMap(consts.MAP_WIDTH, consts.MAP_HEIGHT),
        'messages': [],
        'selection': 0,
        'side_screen': 'HUD',
        'turns': 0,
        'wins': 0,
        'map_console': None,
        'scores': [],
        'mouse_pos': (-1,-1)
    }
    GS['map_console'] = tdl.Console(GS['terrain_map'].width,
                                    GS['terrain_map'].height)

reset_GS()

with open('.gamescores', 'r') as scores:
    for score in scores:
        GS['scores'].append(int(score))

def signal_handler(signal, frame):
    print('SIGINT received, exiting now.')
    exit()

signal.signal(signal.SIGINT, signal_handler)

class Game(tdl.event.App):
    def ev_MOUSEMOVE(self, event):
        GS['mouse_pos'] = event.cell

    def ev_KEYDOWN(self, event):
        global GS
        if event.keychar.upper() == 'Q':
            exit()
        elif GS['side_screen'] == 'INVENTORY':
            if event.keychar.upper() == 'UP':
                GS['selection'] -= 1
                GS['selection'] %= len(GS['player'].inventory)
            elif event.keychar.upper() == 'DOWN':
                GS['selection'] += 1
                GS['selection'] %= len(GS['player'].inventory)
            elif event.keychar.upper() == 'D':
                pos = GS['player'].pos
                item = GS['player'].inventory[GS['selection']][0]
                GS['terrain_map'].dungeon['items'][pos].append(item)
                GS['player'].remove_inventory_item(item)
            elif event.keychar.upper() == 'W':
                GS['player'].inventory[GS['selection']][0].equip(GS['player'])
            elif event.keychar.upper() == 'T':
                GS['player'].inventory[GS['selection']][0].dequip(GS['player'])
            elif event.keychar.upper() == 'I':
                GS['side_screen'] = 'HUD'
            elif event.keychar.isnumeric():
                GS['selection'] = int(event.keychar)
            GS['player'].update_inventory()
        elif GS['screen'] == 'DEATH':
            if event.keychar.upper() == 'R':
                reset_GS()
        elif GS['screen'] == 'INTRO' and len(event.keychar) == 1 or\
                event.keychar.upper() == 'SPACE':
            GS['screen'] = 'CHARSEL'
        elif GS['screen'] == 'CHARSEL':
            if event.keychar.upper() == 'UP':
                GS['selection'] -= 1
                GS['selection'] %= len(races.RACES)+1
            elif event.keychar.upper() == 'DOWN':
                GS['selection'] += 1
                GS['selection'] %= len(races.RACES)+1
            elif event.keychar.isnumeric() and len(event.keychar) == 1:
                GS['selection'] = int(event.keychar)
            elif event.keychar.upper() == 'ENTER':
                racen = GS['selection']-1
                if racen < len(races.RACES) and racen >= 0:
                    selected_race = races.RACES[racen]
                    GS['player'] = player.Player(selected_race)
                    consts.DIFFICULTY = selected_race.suggested_difficulty

                    GS['player'].pos = GS['terrain_map'].generate_new_map()

                    GS['terrain_map'].dungeon['monsters'] = sorted(
                        GS['terrain_map'].dungeon['monsters'], key=lambda m: m.speed)

                    GS['screen'] = 'GAME'
        elif GS['screen'] == 'GAME':
            if event.keychar in consts.GAME_KEYS['M'] and GS['side_screen'] != 'MAN':
                GS['player'].move(event, GS)
            elif event.keychar in consts.GAME_KEYS['A']:
                consts.GAME_KEYS['A'][event.keychar](GS, GS['player'])
            elif event.keychar == '?' and GS['side_screen'] == 'HUD':
                GS['side_screen'] = 'MAN'
            elif event.keychar == '?' and GS['side_screen'] == 'MAN':
                GS['side_screen'] = 'HUD'

        if len(event.keychar) == 1 and not GS['screen'] == 'DEATH':
            utils.monster_turn(GS)
            GS['turns'] += 1

    def ev_QUIT(self, event):
        exit()

    def ev_MOUSEDOWN(self, event):
        if event.button == 'RIGHT':
            t = GS['terrain_map']
            monster = t.monster_at(event.cell)
            item    = event.cell in t.dungeon['items']
            decor   = event.cell in t.dungeon['decor']
            terrain = t.get_type(event.cell)

            obj = terrain.lower()
            if monster:
                obj = 'a ' + monster.name
            elif terrain == 'STONE' and decor:
                obj = 'lichen-covered stone'
            elif item:
                if len(t.dungeon['items'][event.cell]) > 0:
                    obj = t.dungeon['items'][event.cell][0].name
            elif decor:
                if t.dungeon['decor'][event.cell] == 'FM':
                    obj = 'a weed'
                elif t.dungeon['decor'][event.cell] == 'FR':
                    obj = 'flames'
                elif not t.dungeon['decor'][event.cell]:
                    obj = 'floor'
                else:
                    obj = 'hot rocks'

            GS['messages'].insert(0, 'You see ' + obj + ' there.')
            
    def update(self, dt):
        if GS['player'].health <= 0 and not consts.WIZARD_MODE:
            GS['screen'] = 'DEATH'
        draw.draw_screen(GS)
            
Game().run()
